name: nati_kit
description: A robust Flutter UI toolkit with production-ready components, theming, and utilities. Built by Natnael for rapid app development.
version: 1.0.1
homepage: https://github.com/Natnael-Alemseged/nati_kit
repository: https://github.com/Natnael-Alemseged/nati_kit

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  delightful_toast: ^1.1.0
  dio: ^5.9.0
  dio_cookie_manager: ^3.0.1
  cookie_jar: ^4.0.8
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.5.0
  package_info_plus: ^8.1.1
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
